sudo: false
language: node_js
node_js:
  - "7"
  - "6"
  - "4"
install: npm i && (cd examples/simple && npm i)
cache: yarn
script: "npm run lint && npm run test:cov"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
